kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  namespace: default
  labels:
    app: sonar
data:
  SONARQUBE_JDBC_URL: "jdbc:postgresql://sonar-postgres:5432/sonar_db"
  SONARQUBE_JDBC_USERNAME: "postgres"
  SONARQUBE_JDBC_PASSWORD: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
  namespace: default
  labels:
    app: sonar
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:community
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: sonar-config
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          httpGet:
            host:
            scheme: HTTP
            path: /
            port: 9000
      volumes:
      - name: app-pvc
        persistentVolumeClaim:
          claimName: sonar-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
  namespace: default
  labels:
    app: sonar
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 30009
  selector:
    app: sonar
  type: NodePort
---