services:
  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - spring-postgres
    restart: always
    depends_on:
      - database
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - spring-postgres

networks:
  spring-postgres:
volumes:
  pg_data: