kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonar-postgres-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-postgres-map
  namespace: default
  labels:
    app: sonar-postgres
data:
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: postgres
  POSTGRESQL_DATABASE: sonar_db
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-postgres
  namespace: default
  labels:
    app: sonar-postgres
spec:
  ports:
  - port: 5432
    name: sonar-postgres
  selector:
    app: sonar-postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-postgres
  namespace: default
  labels:
    app: sonar-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar-postgres
  template:
    metadata:
      labels:
        app: sonar-postgres
    spec:
      containers:
      - name: sonar-postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: sonar_db
        envFrom:
        - configMapRef:
            name: sonar-postgres-map
        volumeMounts:
        - name: sonar-db-postgres-volume
          mountPath: /bitnami/postgresql
      volumes:
      - name: sonar-db-postgres-volume
        persistentVolumeClaim:
          claimName: sonar-postgres-pvc
---