- name: Create new service account
  hosts: localhost
  tasks:
    # vars:
    #   namespace: kube-system
    #   service_account_name: visitor
    #   is_admin: false

    - name: Create SA
      shell: |
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: {{ service_account_name }}
          namespace: {{ namespace }}

     - name: Set admin role binding
      shell: |
        kubectl apply -f <<EOF
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: {{ service_account_name }}
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - kind: ServiceAccount
          name: {{ service_account_name }}
          namespace: {{ namespace }}
        EOF
      when: {{ is_admin }}
    - name: Create Secret for user with token
      shell: |
        apiVersion: v1
        kind: Secret
        metadata:
          name: secret-{{ service_account_name }}
          namespace: {{ namespace }}
          annotations:
            kubernetes.io/service-account.name: {{ service_account_name }}
        type: kubernetes.io/service-account-token
    - name: Get token
      shell: |
        echo $(kubectl get secret secret-{{ service_account_name }} -n {{ namespace }} -o jsonpath={.data.token} | base64 --decode)

    